/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CTokenRouteImport } from './routes/c.$token'
import { Route as AuthenticatedWorkshopsRouteImport } from './routes/_authenticated/workshops'
import { Route as AuthenticatedPlansRouteImport } from './routes/_authenticated/plans'
import { Route as AuthenticatedFinancialRouteImport } from './routes/_authenticated/financial'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedMotorcyclesIndexRouteImport } from './routes/_authenticated/motorcycles.index'
import { Route as AuthenticatedMotorcyclesNewRouteImport } from './routes/_authenticated/motorcycles.new'
import { Route as AuthenticatedMotorcyclesIdRouteImport } from './routes/_authenticated/motorcycles.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CTokenRoute = CTokenRouteImport.update({
  id: '/c/$token',
  path: '/c/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkshopsRoute = AuthenticatedWorkshopsRouteImport.update({
  id: '/workshops',
  path: '/workshops',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlansRoute = AuthenticatedPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinancialRoute = AuthenticatedFinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMotorcyclesIndexRoute =
  AuthenticatedMotorcyclesIndexRouteImport.update({
    id: '/motorcycles/',
    path: '/motorcycles/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMotorcyclesNewRoute =
  AuthenticatedMotorcyclesNewRouteImport.update({
    id: '/motorcycles/new',
    path: '/motorcycles/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMotorcyclesIdRoute =
  AuthenticatedMotorcyclesIdRouteImport.update({
    id: '/motorcycles/$id',
    path: '/motorcycles/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financial': typeof AuthenticatedFinancialRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/workshops': typeof AuthenticatedWorkshopsRoute
  '/c/$token': typeof CTokenRoute
  '/motorcycles/$id': typeof AuthenticatedMotorcyclesIdRoute
  '/motorcycles/new': typeof AuthenticatedMotorcyclesNewRoute
  '/motorcycles/': typeof AuthenticatedMotorcyclesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financial': typeof AuthenticatedFinancialRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/workshops': typeof AuthenticatedWorkshopsRoute
  '/c/$token': typeof CTokenRoute
  '/motorcycles/$id': typeof AuthenticatedMotorcyclesIdRoute
  '/motorcycles/new': typeof AuthenticatedMotorcyclesNewRoute
  '/motorcycles': typeof AuthenticatedMotorcyclesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/financial': typeof AuthenticatedFinancialRoute
  '/_authenticated/plans': typeof AuthenticatedPlansRoute
  '/_authenticated/workshops': typeof AuthenticatedWorkshopsRoute
  '/c/$token': typeof CTokenRoute
  '/_authenticated/motorcycles/$id': typeof AuthenticatedMotorcyclesIdRoute
  '/_authenticated/motorcycles/new': typeof AuthenticatedMotorcyclesNewRoute
  '/_authenticated/motorcycles/': typeof AuthenticatedMotorcyclesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agenda'
    | '/dashboard'
    | '/financial'
    | '/plans'
    | '/workshops'
    | '/c/$token'
    | '/motorcycles/$id'
    | '/motorcycles/new'
    | '/motorcycles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agenda'
    | '/dashboard'
    | '/financial'
    | '/plans'
    | '/workshops'
    | '/c/$token'
    | '/motorcycles/$id'
    | '/motorcycles/new'
    | '/motorcycles'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agenda'
    | '/_authenticated/dashboard'
    | '/_authenticated/financial'
    | '/_authenticated/plans'
    | '/_authenticated/workshops'
    | '/c/$token'
    | '/_authenticated/motorcycles/$id'
    | '/_authenticated/motorcycles/new'
    | '/_authenticated/motorcycles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CTokenRoute: typeof CTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$token': {
      id: '/c/$token'
      path: '/c/$token'
      fullPath: '/c/$token'
      preLoaderRoute: typeof CTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workshops': {
      id: '/_authenticated/workshops'
      path: '/workshops'
      fullPath: '/workshops'
      preLoaderRoute: typeof AuthenticatedWorkshopsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plans': {
      id: '/_authenticated/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AuthenticatedPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financial': {
      id: '/_authenticated/financial'
      path: '/financial'
      fullPath: '/financial'
      preLoaderRoute: typeof AuthenticatedFinancialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/motorcycles/': {
      id: '/_authenticated/motorcycles/'
      path: '/motorcycles'
      fullPath: '/motorcycles/'
      preLoaderRoute: typeof AuthenticatedMotorcyclesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/motorcycles/new': {
      id: '/_authenticated/motorcycles/new'
      path: '/motorcycles/new'
      fullPath: '/motorcycles/new'
      preLoaderRoute: typeof AuthenticatedMotorcyclesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/motorcycles/$id': {
      id: '/_authenticated/motorcycles/$id'
      path: '/motorcycles/$id'
      fullPath: '/motorcycles/$id'
      preLoaderRoute: typeof AuthenticatedMotorcyclesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinancialRoute: typeof AuthenticatedFinancialRoute
  AuthenticatedPlansRoute: typeof AuthenticatedPlansRoute
  AuthenticatedWorkshopsRoute: typeof AuthenticatedWorkshopsRoute
  AuthenticatedMotorcyclesIdRoute: typeof AuthenticatedMotorcyclesIdRoute
  AuthenticatedMotorcyclesNewRoute: typeof AuthenticatedMotorcyclesNewRoute
  AuthenticatedMotorcyclesIndexRoute: typeof AuthenticatedMotorcyclesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinancialRoute: AuthenticatedFinancialRoute,
  AuthenticatedPlansRoute: AuthenticatedPlansRoute,
  AuthenticatedWorkshopsRoute: AuthenticatedWorkshopsRoute,
  AuthenticatedMotorcyclesIdRoute: AuthenticatedMotorcyclesIdRoute,
  AuthenticatedMotorcyclesNewRoute: AuthenticatedMotorcyclesNewRoute,
  AuthenticatedMotorcyclesIndexRoute: AuthenticatedMotorcyclesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CTokenRoute: CTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
