/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMotorcyclesIndexRouteImport } from './routes/_authenticated/motorcycles.index'
import { Route as AuthenticatedMotorcyclesNewRouteImport } from './routes/_authenticated/motorcycles.new'
import { Route as AuthenticatedMotorcyclesIdRouteImport } from './routes/_authenticated/motorcycles.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMotorcyclesIndexRoute =
  AuthenticatedMotorcyclesIndexRouteImport.update({
    id: '/motorcycles/',
    path: '/motorcycles/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMotorcyclesNewRoute =
  AuthenticatedMotorcyclesNewRouteImport.update({
    id: '/motorcycles/new',
    path: '/motorcycles/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMotorcyclesIdRoute =
  AuthenticatedMotorcyclesIdRouteImport.update({
    id: '/motorcycles/$id',
    path: '/motorcycles/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/motorcycles/$id': typeof AuthenticatedMotorcyclesIdRoute
  '/motorcycles/new': typeof AuthenticatedMotorcyclesNewRoute
  '/motorcycles/': typeof AuthenticatedMotorcyclesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/motorcycles/$id': typeof AuthenticatedMotorcyclesIdRoute
  '/motorcycles/new': typeof AuthenticatedMotorcyclesNewRoute
  '/motorcycles': typeof AuthenticatedMotorcyclesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/motorcycles/$id': typeof AuthenticatedMotorcyclesIdRoute
  '/_authenticated/motorcycles/new': typeof AuthenticatedMotorcyclesNewRoute
  '/_authenticated/motorcycles/': typeof AuthenticatedMotorcyclesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/motorcycles/$id'
    | '/motorcycles/new'
    | '/motorcycles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/motorcycles/$id'
    | '/motorcycles/new'
    | '/motorcycles'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/motorcycles/$id'
    | '/_authenticated/motorcycles/new'
    | '/_authenticated/motorcycles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/motorcycles/': {
      id: '/_authenticated/motorcycles/'
      path: '/motorcycles'
      fullPath: '/motorcycles/'
      preLoaderRoute: typeof AuthenticatedMotorcyclesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/motorcycles/new': {
      id: '/_authenticated/motorcycles/new'
      path: '/motorcycles/new'
      fullPath: '/motorcycles/new'
      preLoaderRoute: typeof AuthenticatedMotorcyclesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/motorcycles/$id': {
      id: '/_authenticated/motorcycles/$id'
      path: '/motorcycles/$id'
      fullPath: '/motorcycles/$id'
      preLoaderRoute: typeof AuthenticatedMotorcyclesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMotorcyclesIdRoute: typeof AuthenticatedMotorcyclesIdRoute
  AuthenticatedMotorcyclesNewRoute: typeof AuthenticatedMotorcyclesNewRoute
  AuthenticatedMotorcyclesIndexRoute: typeof AuthenticatedMotorcyclesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMotorcyclesIdRoute: AuthenticatedMotorcyclesIdRoute,
  AuthenticatedMotorcyclesNewRoute: AuthenticatedMotorcyclesNewRoute,
  AuthenticatedMotorcyclesIndexRoute: AuthenticatedMotorcyclesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
